global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:9090"]
        labels:
          service: api-gateway

  - job_name: producer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["producer:9090"]
        labels:
          service: producer

  - job_name: pdf-extractor
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["pdf-extractor:9090"]
        labels:
          service: pdf-extractor

  - job_name: question-generator
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["question-generator:9090"]
        labels:
          service: question-generator

  - job_name: performance-analyzer
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["performance-analyzer:9090"]
        labels:
          service: performance-analyzer

  - job_name: event-ledger
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["event-ledger:9090"]
        labels:
          service: event-ledger

  - job_name: core-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["core-service:9090"]
        labels:
          service: core-service

  - job_name: keycloak
    metrics_path: /metrics
    static_configs:
      - targets: ["keycloak:9000"]
        labels:
          service: keycloak

  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          service: cadvisor
