spring:
  application:
    name: pdf-extractor

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

kafka:
  bootstrap-servers: localhost:9092

aws:
  s3:
    bucket: your-s3-bucket-name
    region: us-east-1
    access-key: YOUR_AWS_ACCESS_KEY_ID
    secret-key: YOUR_AWS_SECRET_ACCESS_KEY
    path-style-access-enabled: false
