spring:
  application:
    name: pdf-extractor
  main:
    web-application-type: none

kafka:
  bootstrap-servers: localhost:9092

aws:
  s3:
    bucket: your-s3-bucket-name
    region: us-east-1
    access-key: YOUR_AWS_ACCESS_KEY_ID
    secret-key: YOUR_AWS_SECRET_ACCESS_KEY
    path-style-access-enabled: false
